name: Meu Primeiro Workflow no github actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job01:
    runs-on: ubuntu-hosted
    steps:
      - name: Step 1
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: 'dpa0702'
          password: ${{ secrets.secret}}
