name: Meu Primeiro Workflow no github actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v4

      - name: Step 2 - Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: 'dpa0702'
          password: ${{ secrets.secret}}

      - name: Step 3 - Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: 'latest'
          push: true
